services:
  radarr:
    image: lscr.io/linuxserver/radarr:develop
    container_name: radarr
    environment:
      - PUID=1234
      - PGID=1234
      - TZ=America/Los_Angeles
    volumes:
      - ${DATA_PATH}/radarr/config:/config
      - ${STORAGE}:${STORAGE}
    ports:
      - 7878:7878
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
