services:
  freshrss:
    image: lscr.io/linuxserver/freshrss
    container_name: freshrss
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${DATA_PATH}/freshrss/config:/config
    ports:
      - 2980:80
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
