services:
  navidrome:
    image: deluan/navidrome:latest
    user: 1234:1234 # should be owner of volumes
    ports:
      - "4533:4533"
    restart: unless-stopped
    environment:
      # Optional: put your config options customization here. Examples:
      ND_SCANSCHEDULE: 1h
      ND_LOGLEVEL: info  
      ND_SESSIONTIMEOUT: 24h
      ND_BASEURL: ${BASEURL}
      ND_LASTFM_APIKEY: ${LASTFM_APIKEY}
      ND_LASTFM_SECRET: ${LASTFM_SECRET}
    volumes:
      - ${DATA_PATH}/navidrome/data:/data
      - ${MUSIC_PATH}:/music:ro
