
services:
  tautulli:
    image: lscr.io/linuxserver/tautulli
    container_name: tautulli
    environment:
      - PUID=1234
      - PGID=1234
      - TZ=America/Los_Angeles
    volumes:
      - ${DATA_PATH}/tautulli/config:/config
    ports:
      - 8181:8181
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
