version: "2"
services:
    ytdl_material:
        environment: 
            ytdl_mongodb_connection_string: 'mongodb://ytdl-mongo-db:27017'
            ytdl_use_local_db: 'false'
            write_ytdl_config: 'true'
        restart: always
        depends_on:
            - ytdl-mongo-db
        volumes:
            - ${DATA_PATH}/ytdl-material/appdata:/app/appdata
            - ${DATA_PATH}/ytdl-material/audio:/app/audio
            - ${DATA_PATH}/ytdl-material/video:/app/video
            - ${DATA_PATH}/ytdl-material/subscriptions:/app/subscriptions
            - ${DATA_PATH}/ytdl-material/users:/app/users
        ports:
            - "8998:17442"
        image: tzahi12345/youtubedl-material:latest
    ytdl-mongo-db:
        # If you are using a Raspberry Pi, use mongo:4${DATA_PATH}/ytdl-material4${DATA_PATH}/ytdl-material18
        image: mongo:4
        logging:
            driver: "none"          
        container_name: mongo-db
        restart: always
        volumes:
            - ${DATA_PATH}/ytdl-material/db/:/data/db
