services:
  sonarr:
    image: ghcr.io/linuxserver/sonarr:develop
    container_name: sonarr
    environment:
      - PUID=1234
      - PGID=1234
      - TZ=America/Los_Angeles
    volumes:
      - ${DATA_PATH}/sonarr/config:/config
      - ${STORAGE}:${STORAGE}
    ports:
      - 8989:8989
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
