version: '3.3'
services:
    filebrowser:
        volumes:
            - '/storage:/srv' #Directory FileBrowser will use to manage your files
            - '${DATA_PATH}/filebrowser/database:/database/'
            - '${DATA_PATH}/filebrowser/config:/config/'
        environment:
            - PUID=1000
            - PGID=1000
        ports:
            - '8210:80'
        image: 'filebrowser/filebrowser:s6'
        restart: unless-stopped
        labels:
          - "com.centurylinklabs.watchtower.enable=true"
        container_name: filebrowser
