services:
  beszel-agent:
    image: 'henrygd/beszel-agent'
    container_name: 'beszel-agent'
    restart: unless-stopped
    network_mode: host
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      # monitor other disks / partitions by mounting a folder in /extra-filesystems
      - /mnt/disk1/.beszel:/extra-filesystems/disk1:ro
      - /mnt/disk2/.beszel:/extra-filesystems/disk2:ro
      - /mnt/disk3/.beszel:/extra-filesystems/disk3:ro
      - /mnt/disk4/.beszel:/extra-filesystems/disk4:ro
    environment:
      PORT: 45876
      KEY: ${KEY}
