version: '3'

services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: always
    environment:
      DOMAIN: "${DOMAIN}"  # Your domain; vaultwarden needs to know it's https to work properly with attachments
    volumes:
      - ${DATA_PATH}/vaultwarden/vw-data:/data
    ports:
      - 2822:80
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
