---
version: "2.1"
services:
  emulatorjs:
    image: lscr.io/linuxserver/emulatorjs:latest
    container_name: emulatorjs
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
      - SUBFOLDER=/ #optional
    volumes:
      - ${DATA_PATH}/emulatorjs/config:/config
      - ${STORAGE_PATH}/emulatorjs/data:/data
      - ${ROMS_PATH}/:/roms/:ro
    ports:
      - 1200:3000
      - 800:80
      - 4001:4001 #optional
    restart: unless-stopped
