services:
  headscale:
    image: headscale/headscale:latest
    restart: unless-stopped
    container_name: headscale
    ports:
      - "8080:8080"
      - "9080:9090"
    volumes:
      # Please change <CONFIG_PATH> to the fullpath of the config folder just created
      - ${DATA_PATH}/headscale/config:/etc/headscale
    command: serve
