services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Los_Angeles
    volumes:
      - ${DATA_PATH}/prowlarr/config:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    labels:
      - "com.centurylinklabs.watchtower.enable=true"
