services:
  overseerr:
    image: sctx/overseerr:latest
    container_name: overseerr
    environment:
      - LOG_LEVEL=debug
      - TZ=America/Los_Angeles
      - PORT=5055 #optional
    ports:
      - 1055:5055
    volumes:
      - ${DATA_PATH}/overseerr/config:/app/config
    restart: unless-stopped
